---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  attributes:
    apt:
      compile_time_update: true

platforms:
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-14.04_provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-7.0
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]
  driver_config:
    box: opscode-centos-7.0
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-7.0_provisionerless.box
- name: centos-6.5
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.5_provisionerless.box

suites:
- name: varnish3
  excludes:
    - centos-7.0
  run_list:
  - recipe[varnish]
  attributes:
    varnish:
      version: '3.0'
- name: varnish4
  run_list:
  - recipe[varnish]
  attributes:
    varnish:
      version: '4.0'
      log_daemon: false
      
- name: distro_libraries
  includes:
    - ubuntu-14.04
    - centos-7.0
    - centos-6.5
  run_list:
    - recipe[install_varnish::distro_install]
- name: vendor_libraries
  includes:
    - ubuntu-14.04
    - centos-7.0
    - centos-6.5
  run_list:
    - recipe[install_varnish::vendor_install]
